config/routes.rb
Rails.application.routes.draw do
  

  resources :users, only: [:index, :new] do 
    resources :campaigns, only: [:new, :create, :show, :edit, :update] do 
      resources :be_hero, only: [:new, :create] 
      resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :goals, only: [:new, :create, :edit, :update, :destroy]
      resources :rewards, only: [:new, :create, :edit, :update]
      resources :posts, only: [:new, :create, :edit, :update, :destroy] do
        resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    
    resources :profiles, only: [:show, :edit, :update]
    resources :streams, only: [:new, :create, :show, :delete] do
      resources :viewers, only: [:index]
    end
  end

  resources :featured, only: [:index, :show]
  resources :search, only: [:create, :index]
  resources :campaign_setup, only: [:new, :create]

  match '/signout', :to => 'sessions#destroy', via: :delete
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get '/posts/hashtag/:name', to:'posts#hashtags'
  post 'tokens' => "tokens#create"
  get 'home' => 'home#index'
  root 'home#index'

end

app/models/be_hero.rb
class BeHero < ActiveRecord::Base
	attr_accessor :current_step

	def current_step 
		@current_step || steps.first 
	end

	def steps 
		%w[rewardsform braintreeform]
	end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	belongs_to :user 
	belongs_to :goal

	has_many :payments
	has_many :rewards
	has_many :posts, dependent: :destroy 
  has_and_belongs_to_many :tags
  include PgSearch
  multisearchable :against => [:title, :description, :taggings]

  after_create do
    if self.taggings.nil? == false
      campaign = Campaign.find_by(id: self.id)
      #find the campaign ID itself
      hashtags = self.taggings.scan(/#\w+/)
      #scans campaign body that starts with #
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        campaign.tags << tag
      end
    end
  end

  before_update do
    campaign = Campaign.find_by(id: self.id)
    campaign.tags.clear #delete all and add again
    hashtags = self.taggings.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      campaign.tags << tag
    end
  end
	mount_uploaders :campaign_images, PictureUploader
	mount_uploader :cover_photo, AvatarUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :interests
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	has_one :campaign
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	belongs_to :category
	has_many :profile_interests
	has_many :profiles, :through => :profile_interests

end

app/models/model.rb
class Model < ActiveRecord::Base
  mount_uploader :file, ModelUploader
  attr_accessible :file
end

app/models/payment.rb
class Payment < ActiveRecord::Base
belongs_to :reward
belongs_to :user
belongs_to :campaign	
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :campaign
  has_many :comments

  mount_uploaders :post_images, PictureUploader
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :profile_interests
	has_many :interests, :through => :profile_interests
	belongs_to :user
	mount_uploader :avatar, AvatarUploader

	def full_name
	  a = self.first_name.titleize if self.first_name != nil
	  b = self.last_name.titleize if self.last_name != nil
	  if a != nil && b != nil
	  	return "#{a} #{b}"
	  elsif a != nil && b == nil
	  	return "#{a}"
	  elsif a == nil && b != nil
	  	return "#{b}"
	  else
	  	return "N/A"
	  end
	end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :campaign
  has_one :payment
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  before_create do |stream|
    session = OpenTokClient.create_session
    stream.opentok_session_id = session.session_id
  end

  belongs_to :user
  has_many :viewers

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  has_and_belongs_to_many :campaigns
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_one :profile
  has_one :campaign 
  has_one :stream
  has_many :viewers
  has_many :comments
  has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end


  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

  def validate_password
    raise PasswordDoesNotMatch if password_confirmation != password
  end   

class PasswordDoesNotMatch < StandardError; end 

end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
  belongs_to :user
  belongs_to :stream
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
	before_action :require_login

	def new
		@stream = Stream.new
	end

	def create
		params.permit!
		@user = User.find(params[:user_id])
		if Stream.find_by(user_id: @user.id) == nil
			@stream = Stream.create(user_id: @user.id)
			@stream.update(params[:stream])
		else
			@stream = Stream.find_by(user_id: @user.id)
			@stream.update(params[:stream])
		end
		#byebug
		Post.create(campaign_id: @user.campaign.id, body: "#{@user.username} is streaming #{@user.stream.title}! <a href=\"/users/#{@user.id}/streams/#{@user.stream.id}\">View now!</a>")
		redirect_to user_stream_path(current_user, @stream.id)
	end

	def show
		if current_user = User.find(params[:user_id])
	    	@stream     = current_user.stream || current_user.create_stream
	    else
	    	@stream = User.find(params[:user_id]).stream
	    end
        gon.opentok = opentok_data(@stream)
	end

  private

  def opentok_data(stream)
    token = OpenTokClient.generate_token(stream.opentok_session_id)
    { sessionId: stream.opentok_session_id, apiKey: Figaro.env.opentok_api_key, token: token }
  end


end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/streams/new.html.erb
<br>
<br>
<br>
<br>

<%= form_for [:user, @stream] do |f| %>
<%= f.text_field :title %>
<%= f.text_field :description %>
<%= f.submit %>
<% end %>

app/views/streams/show.html.erb
<br>
<%= javascript_include_tag "//static.opentok.com/webrtc/v2.2/js/TB.min.js" %>
<script>
function printMessage(message) {
  $('#messages').append(message + "<br>");
}

$(function() {
    var chatChannel;
    var username;

    function setupChannel() {
        chatChannel.join().then(function(channel) {
            printMessage(username + ' joined the chat.');
        });

        chatChannel.on('messageAdded', function(message) {
            printMessage(message.author + ": " + message.body);
         });
    }

    var $input = $('#chat-input'); 
    $input.on('keydown', function(e) {
        if (e.keyCode == 13) {
            chatChannel.sendMessage($input.val())
            $input.val('');
        }
     });

    $.post("/tokens", function(data) {
    username = data.username;
    var accessManager = new Twilio.AccessManager(data.token);
    var messagingClient = new Twilio.IPMessaging.Client(accessManager);

    messagingClient.getChannelByUniqueName('chat').then(function(channel) {
        if (channel) {
            chatChannel = channel;
            setupChannel();
        } else {
            messagingClient.createChannel({
                uniqueName: 'chat',
                friendlyName: 'Chat Channel' })
            .then(function(channel) {
                chatChannel = channel;
                setupChannel();
            });
        }
    });
});

});
</script>
<div class="col-lg-12 col-sm-12 videobox">
<table>
<tr><td rowspan="2" class="col-lg-3 col-sm-3 videotable">
<br>
    <div class="videopillar">
	<% if current_user == @stream.user %> 
	<% else %>
	<h1><%= @stream.user.username.upcase %>'S STREAM </h1>
	<% end %>
	<h2><%= @stream.title %></h2>
    <h4>by <%= link_to @stream.user.username, user_profile_path(user_id: @stream.user.id, id: @stream.user.profile.id) %></h4>
	<p><%= @stream.description %></p></div>
	</td>
    <td class="col-lg-6 col-sm-6">
    <div style="line-height:15%;">
        <br>
    </div>
	<% if current_user == @stream.user %>
	<div id="publisher" class="video-mask videoplay"><br>
	<% else %>
	<div id="stream" class="video-mask videoplay"></div>
	<% end %></td>
    <td rowspan="2" class="col-lg-3 col-sm-3">
    <br>
    <div class="videopillar">

  <div align="center">
  <h1>HELLO! <span class="glyphicon glyphicon-comment"></span></h1>
  <div id="messages"></div><br>
   <input id="chat-input" class="form-control" type="text" placeholder="Your message goes here..." autofocus/></div></td>
 <tr>
 <td class="col-lg-6 col-sm-6">
    <div class="col-lg-2 col-sm-2"><img src="http://i452.photobucket.com/albums/qq244/missnpk93/speaker_zpsnrfdpnzl.png" width="85px" height="85px"></div>
        <% if current_user == @stream.user %>
            <div class="col-lg-8 col-sm-8">
            <a href="/users/<%= @stream.user.id %>/streams/new" target="_blank"><button type="button" class="btn btn-primary btn-lg col-md-12" style="border-bottom:1px solid #e3e4e5">Edit Stream</button></a>
            <a href="/users/<%= @stream.user.id %>/campaigns/<%= @stream.user.campaign.id %>" target="_blank"><button type="button" class="btn btn-primary btn-lg col-md-12">Visit Campaign</button></a><br></div>
        <% else %>
            <div class="col-lg-8 col-sm-8">
            <a href="/users/<%= @stream.user.id %>/campaigns/<%= @stream.user.campaign.id %>" target="_blank"><button type="button" class="btn btn-primary btn-lg col-md-12" style="border-bottom:1px solid #e3e4e5">Visit Campaign</button></a>
            <a href="/featured" target="_blank"><button type="button" class="btn btn-primary btn-lg col-md-12">View Featured Campaigns</button></a><br></div>
        <% end %>
    <div class="col-lg-2 col-sm-2"><img src="http://i452.photobucket.com/albums/qq244/missnpk93/speaker_zpsnrfdpnzl.png" width="85px" height="85px"></div>
</td></tr>
 </table>
</div>
	</div>
</div>