config/routes.rb
Rails.application.routes.draw do
  

  resources :users, only: [:index, :new] do 
    resources :campaigns, only: [:new, :create, :show, :edit, :update] do 
      resources :be_hero, only: [:new, :create] 
      resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :goals, only: [:new, :create, :edit, :update, :destroy]
      resources :rewards, only: [:new, :create, :edit, :update]
      resources :posts, only: [:new, :create, :edit, :update, :destroy] do
        resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
      resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
        resources :comments, only: [:new, :create, :edit, :update, :destroy]
      end
    end
    
    resources :profiles, only: [:show, :edit, :update]
    resources :streams, only: [:new, :create, :show, :delete] do
      resources :viewers, only: [:index]
    end
  end

  resources :featured, only: [:index, :show]
  resources :search, only: [:create, :index]
  resources :campaign_setup, only: [:new, :create]

  match '/signout', :to => 'sessions#destroy', via: :delete
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get '/posts/hashtag/:name', to:'posts#hashtags'
  post 'tokens' => "tokens#create"
  get 'home' => 'home#index'
  root 'home#index'

end

app/models/be_hero.rb
class BeHero < ActiveRecord::Base
	attr_accessor :current_step

	def current_step 
		@current_step || steps.first 
	end

	def steps 
		%w[rewardsform braintreeform]
	end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	belongs_to :user 
	belongs_to :goal

	has_many :payments
	has_many :rewards
	has_many :posts, dependent: :destroy 
  has_and_belongs_to_many :tags
  include PgSearch
  multisearchable :against => [:title, :description, :taggings]

  after_create do
    if self.taggings.nil? == false
      campaign = Campaign.find_by(id: self.id)
      #find the campaign ID itself
      hashtags = self.taggings.scan(/#\w+/)
      #scans campaign body that starts with #
      hashtags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        campaign.tags << tag
      end
    end
  end

  before_update do
    campaign = Campaign.find_by(id: self.id)
    campaign.tags.clear #delete all and add again
    hashtags = self.taggings.scan(/#\w+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      campaign.tags << tag
    end
  end
	mount_uploaders :campaign_images, PictureUploader
	mount_uploader :cover_photo, AvatarUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :interests
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	has_one :campaign
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	belongs_to :category
	has_many :profile_interests
	has_many :profiles, :through => :profile_interests

end

app/models/model.rb
class Model < ActiveRecord::Base
  mount_uploader :file, ModelUploader
  attr_accessible :file
end

app/models/payment.rb
class Payment < ActiveRecord::Base
belongs_to :reward
belongs_to :user
belongs_to :campaign	
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :campaign
  has_many :comments

  mount_uploaders :post_images, PictureUploader
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :profile_interests
	has_many :interests, :through => :profile_interests
	belongs_to :user
	mount_uploader :avatar, AvatarUploader

	def full_name
	  a = self.first_name.titleize if self.first_name != nil
	  b = self.last_name.titleize if self.last_name != nil
	  if a != nil && b != nil
	  	return "#{a} #{b}"
	  elsif a != nil && b == nil
	  	return "#{a}"
	  elsif a == nil && b != nil
	  	return "#{b}"
	  else
	  	return "N/A"
	  end
	end
end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :campaign
  has_one :payment
end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  before_create do |stream|
    session = OpenTokClient.create_session
    stream.opentok_session_id = session.session_id
  end

  belongs_to :user
  has_many :viewers

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts

  has_and_belongs_to_many :campaigns
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_one :profile
  has_one :campaign 
  has_one :stream
  has_many :viewers
  has_many :comments
  has_many :authentications, :dependent => :destroy

  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end


  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

  def validate_password
    raise PasswordDoesNotMatch if password_confirmation != password
  end   

class PasswordDoesNotMatch < StandardError; end 

end

app/models/viewer.rb
class Viewer < ActiveRecord::Base
  belongs_to :user
  belongs_to :stream
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		params.permit!
		@post = Post.new(posts_params)
		@post.campaign_id = params[:campaign_id]

		respond_to do |format|
      	  if @post.save
        	format.html { redirect_to user_campaign_post_path(user_id:current_user.id, campaign_id:params[:campaign_id], id:@post.id), notice: 'Campaign was successfully created.' }
      	  else
        	format.html { render :new }
      	  end
    	end

		# @post.save
		# @post.update(params[:post])

		# redirect_to user_campaign_path(user_id: @posts.campaign.user.id, id: @posts.campaign.id)

	end

	def show 
		@post = Post.find(params[:id])
		@comment = Comment.new
		
	end 

	def edit 
		
		@user = User.find(params[:user_id])
    	@campaign = Campaign.find(params[:campaign_id])
    	@post = Post.find(params[:id])

	end 

	def update 

		params.permit!

		@post = Post.find(params[:id])
		@post.update(posts_params)

		redirect_to user_campaign_path
	end

	def destroy 

		@post = Post.find(params[:id])
		
		@post.destroy
		redirect_to user_campaign_path
	end 

	private 

	def posts_params
	    params.require(:post).permit(:body, {post_images: []})
	end 
end

# Shows each Campaign Posts and any pictures attached to each post.

# <h2>Some of our New Posts about the Campaign: </h2>

# <% if @campaign.posts.length != 0 %>

#   <% posts = @campaign.posts %>
#   <% posts.each do |t| %>

#     <%= t.body %><br>

#     <% image_num = 0 %>
#       <% while image_num <= t.post_images.length - 1 %>      
#         <img src="<%= t.post_images[image_num].thumb.url %>">
#         <% image_num += 1 %>
#       <% end %>

#   <% end %>
# <% end %>

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_for(current_user, @campaign, @post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= link_to 'Back to Post', user_campaign_post_path %> 
<%= link_to 'Back to Campaign', user_campaign_path %>

<h1>Edit your Post</h1>

<%= form_for [@user, @campaign, @post] do |f| %>

<p>Post here:<br>
    <%= f.text_field :body %></p> 

<p><%= f.label :Add_Images_To_New_Post %> <br>
    <%= f.file_field :post_images, multiple: true %> </p>

    <%= f.submit "Edit Post"%>

<% end %>

<%= link_to 'Delete Post', user_campaign_post_path(campaign_id:params[:campaign_id], id:params[:id]), :method => :delete, data: { confirm: "Are you sure to delete this post?" } %>

app/views/posts/hashtags.html.erb
<p id="notice"><%= notice %></p>

<h1>Words tagged</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= render_with_hashtags(post.body) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= render_with_hashtags(post.body) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_user_campaign_post_path(user_id: params[:user_id], campaign_id: params[:campaign_id], id:@post) %> |
<%= link_to 'Return to Campaign Page', user_campaign_path(user_id: params[:user_id], id: params[:campaign_id])%> <br>

<% if current_user.id == @post.campaign.user_id %>
    <%= link_to 'Edit Post', edit_user_campaign_post_path(campaign_id: params[:campaign_id], id: params[:id])%>
    <%= link_to 'Delete Post', user_campaign_post_path(campaign_id: params[:campaign_id], id: params[:id]), :method => :delete, data: { confirm: "Are you sure to delete this post?" } %>
<% end %> <br>

<%= @post.body %> <br>

<%= form_for(@comment, :url => user_campaign_post_comments_path(user_id: current_user.id, campaign_id: params[:campaign_id], post_id: @post.id)) do |f| %>
	<p>
        <%= f.text_field :body %>
        <%= f.submit %>
    </p>
<% end %>

<% @post.comments.each do |c|%> 
	<%= c.body %> <%= c.user.email %><br>
	<% if current_user.id = c.user_id %>
	  <%= link_to 'Edit Comment', edit_user_campaign_post_comment_path(user_id: c.user_id, post_id: c.post_id, id: c.id)%>
      <%= link_to 'Delete Comment', user_campaign_post_comment_path(user_id: c.user_id, post_id: c.post_id, id: c.id), :method => :delete, data: { confirm: "Are you sure to delete this post?" } %>
      <br>
    <% end %>

<% end %>

<% image_num = 0 %>
  <% while image_num <= @post.post_images.length - 1 %>      
    <img src="<%= @post.post_images[image_num].url %>">
    <% image_num += 1 %>
  <% end %>